name: Deploy via Pelican on GitHub pages

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '5 6 * * *'

jobs:
  pelican:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/peru
        key: ${{ runner.os }}-peru-${{ hashFiles('**/peru.yaml/*') }}
        restore-keys: |
          ${{ runner.os }}-peru-

    - uses: Logout22/gh-pages-pelican-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: content
        PELICAN_CONFIG_FILE: publishconf.py
